version: "3.9"
services:
  rabbit_service:
    container_name: rabbit_mq
    image: rabbitmq:3.12.13-management
    environment:
      - RABBIT_DEFAULT_USER=guest
      - RABBIT_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672
  
  redis_server:
    container_name: redis
    image: redis:latest
    environment:
      - REDIS_PORT=6379
    ports:
      - 6379:6379
